updated cmake

diff --git a/.github/workflows/cmake-single-platform.yml b/.github/workflows/cmake-single-platform.yml
--- a/.github/workflows/cmake-single-platform.yml
+++ b/.github/workflows/cmake-single-platform.yml
@@ -46,11 +46,11 @@ jobs:
         run: |
           cd Group\ 01/
           printf '3\n0\n' | ./stage1exe "t3.txt" "output.txt"
-          if [ -f errors.txt ] && [ -s errors.txt ]; then
-              echo "File is not empty."
-          else
-              echo "File is empty or does not exist."
+          if [ ! -f errors.txt ] || [ -s errors.txt ]; then
+              echo "Errors file does not exist or is non empty."
               exit 1
+          else
+              echo "File is empty! No errors."
           fi
         shell: bash
         
@@ -58,11 +58,11 @@ jobs:
         run: |
           cd Group\ 01/
           printf '3\n0\n' | ./stage1exe "t4.txt" "output.txt"
-          if [ -f errors.txt ] && [ -s errors.txt ]; then
-              echo "File is not empty."
-          else
-              echo "File is empty or does not exist."
+          if [ ! -f errors.txt ] || [ -s errors.txt ]; then
+              echo "Errors file does not exist or is non empty."
               exit 1
+          else
+              echo "File is empty! No errors."
           fi
         shell: bash
         
@@ -70,11 +70,11 @@ jobs:
         run: |
           cd Group\ 01/
           printf '3\n0\n' | ./stage1exe "t5.txt" "output.txt"
-          if [ -f errors.txt ] && [ -s errors.txt ]; then
-              echo "File is not empty."
-          else
-              echo "File is empty or does not exist."
+          if [ ! -f errors.txt ] || [ -s errors.txt ]; then
+              echo "Errors file does not exist or is non empty."
               exit 1
+          else
+              echo "File is empty! No errors."
           fi
         shell: bash
 
@@ -86,5 +86,7 @@ jobs:
               echo "File is not empty."
           else
               echo "File is empty or does not exist."
+              exit 1
+
           fi
         shell: bash
